  # Frontend Service
services:
  frontend:
    container_name: pro-frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
