  # Frontend Service
  frontend:
    image: seiddk/pro-frontend:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

  # Backend Service
  backend:
    image: your-backend-image:latest # Replace with your actual backend image
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network
    depends_on:
      - db

  # Database Service
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

# Define persistent volumes
volumes:
  db-data:
