name: Backend CI
on:
  push:
    paths: ['back/**']
  pull_request:
    paths: ['back/**']
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4
      - name: Install & Test
        run: |
          npm install
          npm test
