name: Backend CI

on:
  push:
    paths: ['back/**']
  pull_request:
    paths: ['back/**']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './back/package-lock.json'

      - name: Install & Test
        run: |
          npm install
          npm test
