name: Monorepo CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changes:
    name: Detect Changed Folders
    runs-on: ubuntu-latest
    outputs:
      front: ${{ steps.filter.outputs.front }}
      back: ${{ steps.filter.outputs.back }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.base_ref || github.ref_name }}
          filters: |
            front:
              - 'front/**'
            back:
              - 'back/**'

  frontend-ci:
    name: Frontend CI
    needs: changes
    if: ${{ needs.changes.outputs.front == 'true' }}
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./front
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4   
      - name: Install & Test
          run: |
            echo "Where am I?"
            pwd
            echo "What is in the current directory?"
            ls -F
            echo "Does the vitest binary exist in node_modules?"
            ls -l node_modules/.bin/vitest
            echo "Running tests now..."
            npm run test
#############################################################################################3
  backend-ci:
    name: Backend CI
    needs: changes
    if: ${{ needs.changes.outputs.back == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install & Test
        run: |
          npm ci
          npm run test
