name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]   # must match CI workflow name exactly
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository,
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------------------------
      # FRONTEND IMAGE BUILD
      # -------------------------
      - name: List files to debug paths
        run: |
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pro-frontend:latest
#tags: ${{ secrets.DOCKER_USERNAME }}/spare-frontend:${{ github.sha }}     for image version control and followip live ! 
# but the :latest  this tag will make every version and image updadets for each commit same 
#,...not easy for tracing error

  deploy-to-ec2:
    needs: build-and-push  ##means this deply to ec2 job needs build and push to be already finished above !
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # <---because the docker-compose.yml file is inside the git-repository

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7     #this instruction => copy docker-compose to EC2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/pro" # This creates the directory and puts the file inside...=> pro/docker-compose.yml
          overwrite: true
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # No need to decode or chmod manually; this action handles it in memory.
          script: |
            set -e 
            export PATH=$PATH:/usr/bin:/usr/local/bin
            # 1. Create the directory if it doesn't exist
            mkdir -p ~/pro
            echo "🔹 Logging into Docker Hub..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | /usr/bin/docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # 2. IMPORTANT: You must move your docker-compose.yml to the EC2.
            # If it's already there, we proceed:
            cd ~/pro
            echo "🔹 Pulling and Updating..."
            /usr/bin/docker compose pull
            /usr/bin/docker compose up -d
