name: Frontend CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

      - name: Build App
        run: npm run build
